all: main.cpp move.cpp utility.cpp
	g++ -std=c++11 main.cpp move.cpp utility.cpp -o ../AbsolverDeckMapper -DSFML_STATIC -I C:\sfml-static\SFML\include -L C:\sfml-static\SFML\lib -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lwinmm -lgdi32 -lfreetype -ljpeg -static-libgcc -static-libstdc++
